# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import memory_pb2 as memory__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryStub(object):
    """Memory service manages persistent vector + ledger + context storage
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SemanticSearch = channel.unary_unary(
                '/memory.v1.Memory/SemanticSearch',
                request_serializer=memory__pb2.SemanticSearchRequest.SerializeToString,
                response_deserializer=memory__pb2.SemanticSearchResponse.FromString,
                _registered_method=True)
        self.QueryLedger = channel.unary_unary(
                '/memory.v1.Memory/QueryLedger',
                request_serializer=memory__pb2.LedgerQueryRequest.SerializeToString,
                response_deserializer=memory__pb2.LedgerQueryResponse.FromString,
                _registered_method=True)
        self.WriteVector = channel.unary_unary(
                '/memory.v1.Memory/WriteVector',
                request_serializer=memory__pb2.WriteVectorRequest.SerializeToString,
                response_deserializer=memory__pb2.WriteVectorResponse.FromString,
                _registered_method=True)
        self.WriteLedger = channel.unary_unary(
                '/memory.v1.Memory/WriteLedger',
                request_serializer=memory__pb2.WriteLedgerRequest.SerializeToString,
                response_deserializer=memory__pb2.WriteLedgerResponse.FromString,
                _registered_method=True)


class MemoryServicer(object):
    """Memory service manages persistent vector + ledger + context storage
    """

    def SemanticSearch(self, request, context):
        """SemanticSearch finds similar vectors (e.g., PR history, failure patterns)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryLedger(self, request, context):
        """QueryLedger searches immutable action log
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteVector(self, request, context):
        """WriteVector stores semantic fact
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteLedger(self, request, context):
        """WriteLedger commits action to log (Watchdog primary use)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SemanticSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticSearch,
                    request_deserializer=memory__pb2.SemanticSearchRequest.FromString,
                    response_serializer=memory__pb2.SemanticSearchResponse.SerializeToString,
            ),
            'QueryLedger': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryLedger,
                    request_deserializer=memory__pb2.LedgerQueryRequest.FromString,
                    response_serializer=memory__pb2.LedgerQueryResponse.SerializeToString,
            ),
            'WriteVector': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteVector,
                    request_deserializer=memory__pb2.WriteVectorRequest.FromString,
                    response_serializer=memory__pb2.WriteVectorResponse.SerializeToString,
            ),
            'WriteLedger': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteLedger,
                    request_deserializer=memory__pb2.WriteLedgerRequest.FromString,
                    response_serializer=memory__pb2.WriteLedgerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memory.v1.Memory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('memory.v1.Memory', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Memory(object):
    """Memory service manages persistent vector + ledger + context storage
    """

    @staticmethod
    def SemanticSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.Memory/SemanticSearch',
            memory__pb2.SemanticSearchRequest.SerializeToString,
            memory__pb2.SemanticSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryLedger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.Memory/QueryLedger',
            memory__pb2.LedgerQueryRequest.SerializeToString,
            memory__pb2.LedgerQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.Memory/WriteVector',
            memory__pb2.WriteVectorRequest.SerializeToString,
            memory__pb2.WriteVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteLedger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/memory.v1.Memory/WriteLedger',
            memory__pb2.WriteLedgerRequest.SerializeToString,
            memory__pb2.WriteLedgerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
