# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import muscle_pb2 as muscle__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in muscle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MuscleStub(object):
    """MuscleService: Stateless inference endpoint on Win11
    ====================================================
    The Muscle is a pure compute worker. It receives prompts and returns tokens.
    NO state persistence, NO filesystem access, NO decision-making.
    The Pi (Vault) controls all I/O and validation.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateResponse = channel.unary_stream(
                '/muscle.api.Muscle/GenerateResponse',
                request_serializer=muscle__pb2.PromptRequest.SerializeToString,
                response_deserializer=muscle__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/muscle.api.Muscle/Health',
                request_serializer=muscle__pb2.HealthRequest.SerializeToString,
                response_deserializer=muscle__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetActivityStatus = channel.unary_unary(
                '/muscle.api.Muscle/GetActivityStatus',
                request_serializer=muscle__pb2.ActivityStatusRequest.SerializeToString,
                response_deserializer=muscle__pb2.ActivityStatusResponse.FromString,
                _registered_method=True)


class MuscleServicer(object):
    """MuscleService: Stateless inference endpoint on Win11
    ====================================================
    The Muscle is a pure compute worker. It receives prompts and returns tokens.
    NO state persistence, NO filesystem access, NO decision-making.
    The Pi (Vault) controls all I/O and validation.

    """

    def GenerateResponse(self, request, context):
        """GenerateResponse: Stream tokens from Pi prompt to Muscle
        The Pi sends the prompt once; Muscle streams token responses.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health: Liveness check from Pi
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActivityStatus(self, request, context):
        """GetActivityStatus: Pi reads current activity/queue state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MuscleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateResponse': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateResponse,
                    request_deserializer=muscle__pb2.PromptRequest.FromString,
                    response_serializer=muscle__pb2.TokenResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=muscle__pb2.HealthRequest.FromString,
                    response_serializer=muscle__pb2.HealthResponse.SerializeToString,
            ),
            'GetActivityStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActivityStatus,
                    request_deserializer=muscle__pb2.ActivityStatusRequest.FromString,
                    response_serializer=muscle__pb2.ActivityStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'muscle.api.Muscle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('muscle.api.Muscle', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Muscle(object):
    """MuscleService: Stateless inference endpoint on Win11
    ====================================================
    The Muscle is a pure compute worker. It receives prompts and returns tokens.
    NO state persistence, NO filesystem access, NO decision-making.
    The Pi (Vault) controls all I/O and validation.

    """

    @staticmethod
    def GenerateResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/muscle.api.Muscle/GenerateResponse',
            muscle__pb2.PromptRequest.SerializeToString,
            muscle__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/muscle.api.Muscle/Health',
            muscle__pb2.HealthRequest.SerializeToString,
            muscle__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActivityStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/muscle.api.Muscle/GetActivityStatus',
            muscle__pb2.ActivityStatusRequest.SerializeToString,
            muscle__pb2.ActivityStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
