# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sandbox_pb2 as sandbox__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxStub(object):
    """Sandbox service enables dry-run execution and prediction validation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunDryOp = channel.unary_unary(
                '/sandbox.v1.Sandbox/RunDryOp',
                request_serializer=sandbox__pb2.RunDryOpRequest.SerializeToString,
                response_deserializer=sandbox__pb2.RunDryOpResponse.FromString,
                _registered_method=True)
        self.RecordBaseline = channel.unary_unary(
                '/sandbox.v1.Sandbox/RecordBaseline',
                request_serializer=sandbox__pb2.RecordBaselineRequest.SerializeToString,
                response_deserializer=sandbox__pb2.RecordBaselineResponse.FromString,
                _registered_method=True)
        self.CheckCanaryEligibility = channel.unary_unary(
                '/sandbox.v1.Sandbox/CheckCanaryEligibility',
                request_serializer=sandbox__pb2.CheckCanaryEligibilityRequest.SerializeToString,
                response_deserializer=sandbox__pb2.CheckCanaryEligibilityResponse.FromString,
                _registered_method=True)


class SandboxServicer(object):
    """Sandbox service enables dry-run execution and prediction validation
    """

    def RunDryOp(self, request, context):
        """RunDryOp executes Muscle in isolation (unmetered, no approval)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordBaseline(self, request, context):
        """RecordBaseline stores Shadow's 24h baseline prediction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckCanaryEligibility(self, request, context):
        """CheckCanaryEligibility evaluates Shadow promotion logic
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunDryOp': grpc.unary_unary_rpc_method_handler(
                    servicer.RunDryOp,
                    request_deserializer=sandbox__pb2.RunDryOpRequest.FromString,
                    response_serializer=sandbox__pb2.RunDryOpResponse.SerializeToString,
            ),
            'RecordBaseline': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordBaseline,
                    request_deserializer=sandbox__pb2.RecordBaselineRequest.FromString,
                    response_serializer=sandbox__pb2.RecordBaselineResponse.SerializeToString,
            ),
            'CheckCanaryEligibility': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCanaryEligibility,
                    request_deserializer=sandbox__pb2.CheckCanaryEligibilityRequest.FromString,
                    response_serializer=sandbox__pb2.CheckCanaryEligibilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sandbox.v1.Sandbox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sandbox.v1.Sandbox', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sandbox(object):
    """Sandbox service enables dry-run execution and prediction validation
    """

    @staticmethod
    def RunDryOp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.Sandbox/RunDryOp',
            sandbox__pb2.RunDryOpRequest.SerializeToString,
            sandbox__pb2.RunDryOpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordBaseline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.Sandbox/RecordBaseline',
            sandbox__pb2.RecordBaselineRequest.SerializeToString,
            sandbox__pb2.RecordBaselineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckCanaryEligibility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.v1.Sandbox/CheckCanaryEligibility',
            sandbox__pb2.CheckCanaryEligibilityRequest.SerializeToString,
            sandbox__pb2.CheckCanaryEligibilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
