# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import shadow_pb2 as shadow__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shadow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShadowStub(object):
    """ShadowService: Dry-Run Validator on Pi (Raspberry Pi)
    =====================================================
    Shadow runs proposed code changes WITHOUT executing them for real.
    It predicts outcomes: "If we merge this PR, will the agent still work?"
    Uses: static analysis, symbolic execution, test runs in sandbox.
    Result: Vault uses this to decide whether to merge.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateProposal = channel.unary_unary(
                '/shadow.api.Shadow/ValidateProposal',
                request_serializer=shadow__pb2.ValidationRequest.SerializeToString,
                response_deserializer=shadow__pb2.ValidationResponse.FromString,
                _registered_method=True)
        self.RecordOutcome = channel.unary_unary(
                '/shadow.api.Shadow/RecordOutcome',
                request_serializer=shadow__pb2.OutcomeReport.SerializeToString,
                response_deserializer=shadow__pb2.OutcomeRecorded.FromString,
                _registered_method=True)
        self.QueryReadiness = channel.unary_unary(
                '/shadow.api.Shadow/QueryReadiness',
                request_serializer=shadow__pb2.ReadinessQuery.SerializeToString,
                response_deserializer=shadow__pb2.ReadinessStatus.FromString,
                _registered_method=True)


class ShadowServicer(object):
    """ShadowService: Dry-Run Validator on Pi (Raspberry Pi)
    =====================================================
    Shadow runs proposed code changes WITHOUT executing them for real.
    It predicts outcomes: "If we merge this PR, will the agent still work?"
    Uses: static analysis, symbolic execution, test runs in sandbox.
    Result: Vault uses this to decide whether to merge.

    """

    def ValidateProposal(self, request, context):
        """ValidateProposal: Dry-run a code change before merge
        Returns: Predicted outcome, confidence, any issues found
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordOutcome(self, request, context):
        """RecordOutcome: After execution, log what actually happened
        Shadow learns by comparing prediction vs. reality
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryReadiness(self, request, context):
        """QueryReadiness: Is new Muscle version ready for 24h observation period?
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShadowServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateProposal,
                    request_deserializer=shadow__pb2.ValidationRequest.FromString,
                    response_serializer=shadow__pb2.ValidationResponse.SerializeToString,
            ),
            'RecordOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordOutcome,
                    request_deserializer=shadow__pb2.OutcomeReport.FromString,
                    response_serializer=shadow__pb2.OutcomeRecorded.SerializeToString,
            ),
            'QueryReadiness': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryReadiness,
                    request_deserializer=shadow__pb2.ReadinessQuery.FromString,
                    response_serializer=shadow__pb2.ReadinessStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shadow.api.Shadow', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shadow.api.Shadow', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Shadow(object):
    """ShadowService: Dry-Run Validator on Pi (Raspberry Pi)
    =====================================================
    Shadow runs proposed code changes WITHOUT executing them for real.
    It predicts outcomes: "If we merge this PR, will the agent still work?"
    Uses: static analysis, symbolic execution, test runs in sandbox.
    Result: Vault uses this to decide whether to merge.

    """

    @staticmethod
    def ValidateProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shadow.api.Shadow/ValidateProposal',
            shadow__pb2.ValidationRequest.SerializeToString,
            shadow__pb2.ValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shadow.api.Shadow/RecordOutcome',
            shadow__pb2.OutcomeReport.SerializeToString,
            shadow__pb2.OutcomeRecorded.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryReadiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shadow.api.Shadow/QueryReadiness',
            shadow__pb2.ReadinessQuery.SerializeToString,
            shadow__pb2.ReadinessStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
