# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vault_pb2 as vault__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vault_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VaultStub(object):
    """VaultService: Orchestrator & Decision Engine on Pi (Raspberry Pi)
    ==================================================================
    The Vault receives processing requests from the API (Mac/iPhone) and:
    1. Routes reasoning to Win11 Muscle (stateless)
    2. Validates & signs responses (cryptographic approval)
    3. Routes code to Shadow (dry-run validation)
    4. Executes approved actions (GitHub, filesystem, etc.)
    5. Manages all secrets, rate limits, audit logs

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessPrompt = channel.unary_unary(
                '/vault.api.Vault/ProcessPrompt',
                request_serializer=vault__pb2.VaultPromptRequest.SerializeToString,
                response_deserializer=vault__pb2.VaultResponse.FromString,
                _registered_method=True)
        self.ApproveAction = channel.unary_unary(
                '/vault.api.Vault/ApproveAction',
                request_serializer=vault__pb2.ApprovalRequest.SerializeToString,
                response_deserializer=vault__pb2.ExecutionResponse.FromString,
                _registered_method=True)
        self.QueryPolicy = channel.unary_unary(
                '/vault.api.Vault/QueryPolicy',
                request_serializer=vault__pb2.PolicyQueryRequest.SerializeToString,
                response_deserializer=vault__pb2.PolicyState.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/vault.api.Vault/Health',
                request_serializer=vault__pb2.HealthCheck.SerializeToString,
                response_deserializer=vault__pb2.HealthStatus.FromString,
                _registered_method=True)


class VaultServicer(object):
    """VaultService: Orchestrator & Decision Engine on Pi (Raspberry Pi)
    ==================================================================
    The Vault receives processing requests from the API (Mac/iPhone) and:
    1. Routes reasoning to Win11 Muscle (stateless)
    2. Validates & signs responses (cryptographic approval)
    3. Routes code to Shadow (dry-run validation)
    4. Executes approved actions (GitHub, filesystem, etc.)
    5. Manages all secrets, rate limits, audit logs

    """

    def ProcessPrompt(self, request, context):
        """ProcessPrompt: Main entry point for agent requests
        Returns: Either direct response (Tier 1/2) or PR/action for approval
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveAction(self, request, context):
        """ApproveAction: Sign & execute (rarely needed; most auto-approve in permissive mode)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPolicy(self, request, context):
        """QueryPolicy: Get current governance state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health: Watchdog liveness check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VaultServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPrompt,
                    request_deserializer=vault__pb2.VaultPromptRequest.FromString,
                    response_serializer=vault__pb2.VaultResponse.SerializeToString,
            ),
            'ApproveAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveAction,
                    request_deserializer=vault__pb2.ApprovalRequest.FromString,
                    response_serializer=vault__pb2.ExecutionResponse.SerializeToString,
            ),
            'QueryPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPolicy,
                    request_deserializer=vault__pb2.PolicyQueryRequest.FromString,
                    response_serializer=vault__pb2.PolicyState.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=vault__pb2.HealthCheck.FromString,
                    response_serializer=vault__pb2.HealthStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vault.api.Vault', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vault.api.Vault', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Vault(object):
    """VaultService: Orchestrator & Decision Engine on Pi (Raspberry Pi)
    ==================================================================
    The Vault receives processing requests from the API (Mac/iPhone) and:
    1. Routes reasoning to Win11 Muscle (stateless)
    2. Validates & signs responses (cryptographic approval)
    3. Routes code to Shadow (dry-run validation)
    4. Executes approved actions (GitHub, filesystem, etc.)
    5. Manages all secrets, rate limits, audit logs

    """

    @staticmethod
    def ProcessPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vault.api.Vault/ProcessPrompt',
            vault__pb2.VaultPromptRequest.SerializeToString,
            vault__pb2.VaultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vault.api.Vault/ApproveAction',
            vault__pb2.ApprovalRequest.SerializeToString,
            vault__pb2.ExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vault.api.Vault/QueryPolicy',
            vault__pb2.PolicyQueryRequest.SerializeToString,
            vault__pb2.PolicyState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vault.api.Vault/Health',
            vault__pb2.HealthCheck.SerializeToString,
            vault__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
