# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import watchdog_pb2 as watchdog__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in watchdog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WatchdogStub(object):
    """WatchdogService: Health monitor and rollback controller on Pi
    =============================================================
    Win11 Muscle pushes runtime GPU/performance metrics to Watchdog.
    Watchdog decides whether to trigger rollback and writes retrospectives.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportMetrics = channel.unary_unary(
                '/watchdog.v1.Watchdog/ReportMetrics',
                request_serializer=watchdog__pb2.MetricsReport.SerializeToString,
                response_deserializer=watchdog__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/watchdog.v1.Watchdog/Health',
                request_serializer=watchdog__pb2.WatchdogHealthCheck.SerializeToString,
                response_deserializer=watchdog__pb2.WatchdogHealthStatus.FromString,
                _registered_method=True)


class WatchdogServicer(object):
    """WatchdogService: Health monitor and rollback controller on Pi
    =============================================================
    Win11 Muscle pushes runtime GPU/performance metrics to Watchdog.
    Watchdog decides whether to trigger rollback and writes retrospectives.

    """

    def ReportMetrics(self, request, context):
        """ReportMetrics: Muscle pushes runtime metrics each request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health: Self-liveness check for external probing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchdogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportMetrics,
                    request_deserializer=watchdog__pb2.MetricsReport.FromString,
                    response_serializer=watchdog__pb2.MetricsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=watchdog__pb2.WatchdogHealthCheck.FromString,
                    response_serializer=watchdog__pb2.WatchdogHealthStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'watchdog.v1.Watchdog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('watchdog.v1.Watchdog', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Watchdog(object):
    """WatchdogService: Health monitor and rollback controller on Pi
    =============================================================
    Win11 Muscle pushes runtime GPU/performance metrics to Watchdog.
    Watchdog decides whether to trigger rollback and writes retrospectives.

    """

    @staticmethod
    def ReportMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/watchdog.v1.Watchdog/ReportMetrics',
            watchdog__pb2.MetricsReport.SerializeToString,
            watchdog__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/watchdog.v1.Watchdog/Health',
            watchdog__pb2.WatchdogHealthCheck.SerializeToString,
            watchdog__pb2.WatchdogHealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
