# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: watchdog.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'watchdog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ewatchdog.proto\x12\x0bwatchdog.v1\"\x9a\x01\n\rMetricsReport\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nerror_rate\x18\x02 \x01(\x02\x12\x16\n\x0elatency_p99_ms\x18\x03 \x01(\x03\x12\x12\n\ngpu_temp_c\x18\x04 \x01(\x02\x12\x1f\n\x17gpu_memory_available_mb\x18\x05 \x01(\x02\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x03\"P\n\x0fMetricsResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x17\n\x0fshould_rollback\x18\x02 \x01(\x08\x12\x0e\n\x06reason\x18\x03 \x01(\t\">\n\x13WatchdogHealthCheck\x12\x11\n\tcaller_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\"\xa3\x01\n\x14WatchdogHealthStatus\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x15\n\ractive_alerts\x18\x02 \x01(\x05\x12\x1e\n\x16retrospectives_written\x18\x03 \x01(\x03\x12\x1b\n\x13rollbacks_triggered\x18\x04 \x01(\x03\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x06 \x01(\x03\x32\xa4\x01\n\x08Watchdog\x12I\n\rReportMetrics\x12\x1a.watchdog.v1.MetricsReport\x1a\x1c.watchdog.v1.MetricsResponse\x12M\n\x06Health\x12 .watchdog.v1.WatchdogHealthCheck\x1a!.watchdog.v1.WatchdogHealthStatusB+Z)github.com/ja/agent/internal/api/watchdogb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watchdog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/ja/agent/internal/api/watchdog'
  _globals['_METRICSREPORT']._serialized_start=32
  _globals['_METRICSREPORT']._serialized_end=186
  _globals['_METRICSRESPONSE']._serialized_start=188
  _globals['_METRICSRESPONSE']._serialized_end=268
  _globals['_WATCHDOGHEALTHCHECK']._serialized_start=270
  _globals['_WATCHDOGHEALTHCHECK']._serialized_end=332
  _globals['_WATCHDOGHEALTHSTATUS']._serialized_start=335
  _globals['_WATCHDOGHEALTHSTATUS']._serialized_end=498
  _globals['_WATCHDOG']._serialized_start=501
  _globals['_WATCHDOG']._serialized_end=665
# @@protoc_insertion_point(module_scope)
