"""
Integration tests for the full Vault approval flow.

These tests start a real in-process gRPC server (insecure, random port)
and a VaultService backed by mocked DB/Redis so they run without
external infrastructure.

Test coverage:
  T1 prompt  → auto-approved immediately
  T4 prompt  → rejected (rate-limit mock returns burst count)
  T3 prompt  → PENDING_MFA path, then ApproveAction resumes it
"""

import asyncio
import sys
import uuid
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import grpc
import pytest
import pytest_asyncio

# Make pb2 stubs importable (generated by scripts/gen_protos.sh)
_PROTO_DIR = Path(__file__).resolve().parent.parent.parent / "internal" / "api"
if str(_PROTO_DIR) not in sys.path:
    sys.path.insert(0, str(_PROTO_DIR))

try:
    import vault_pb2
    import vault_pb2_grpc
    _PB2_AVAILABLE = True
except ImportError:
    _PB2_AVAILABLE = False

pytestmark = pytest.mark.skipif(
    not _PB2_AVAILABLE,
    reason="vault_pb2 stubs not generated — run scripts/gen_protos.sh first",
)


# ── Fixtures ──────────────────────────────────────────────────────────────────

@pytest_asyncio.fixture
async def vault_service(mock_ledger, mock_context_manager, mock_graph_client):
    """VaultService with all I/O mocked."""
    from cmd.vault.main import VaultService

    svc = VaultService.__new__(VaultService)
    svc.ledger = mock_ledger
    svc.context = mock_context_manager
    svc.graph_client = mock_graph_client
    svc.GRPC_HOST = "127.0.0.1"
    svc.GRPC_PORT = 0  # assigned dynamically below

    # Mock LangGraphVault
    lg = AsyncMock()
    lg.process_request = AsyncMock(return_value=(True, "Tier 1 auto-approved", 1))
    lg.resume_after_mfa = AsyncMock(return_value=(True, "Human approved", 3))
    svc._lg_vault = lg

    return svc


@pytest_asyncio.fixture
async def grpc_server_and_stub(vault_service):
    """Start an in-process Vault gRPC server and return (server, stub)."""
    from cmd.vault.grpc_server import VaultServicer

    server = grpc.aio.server()
    servicer = VaultServicer(vault_service)
    vault_pb2_grpc.add_VaultServicer_to_server(servicer, server)
    port = server.add_insecure_port("127.0.0.1:0")
    await server.start()

    channel = grpc.aio.insecure_channel(f"127.0.0.1:{port}")
    stub = vault_pb2_grpc.VaultStub(channel)

    yield server, stub

    await channel.close()
    await server.stop(grace=0)


# ── Tests ─────────────────────────────────────────────────────────────────────

class TestTier1AutoApprove:
    @pytest.mark.asyncio
    async def test_direct_response_for_tier1(self, grpc_server_and_stub):
        _, stub = grpc_server_and_stub
        req = vault_pb2.VaultPromptRequest(
            user_id="test-user",
            session_id=str(uuid.uuid4()),
            prompt="List files in the project",
            domain="research",
            tier=vault_pb2.TIER_1,
        )
        response = await stub.ProcessPrompt(req)
        assert response.type == vault_pb2.DIRECT
        assert response.approval == vault_pb2.APPROVED


class TestTier4Rejected:
    @pytest.mark.asyncio
    async def test_tier4_burst_rejected(
        self, vault_service, grpc_server_and_stub, mock_context_manager
    ):
        _, stub = grpc_server_and_stub
        # Make LangGraph return a rejection
        vault_service._lg_vault.process_request = AsyncMock(
            return_value=(False, "Tier 4 rate limit exceeded", 4)
        )

        req = vault_pb2.VaultPromptRequest(
            user_id="test-user",
            session_id=str(uuid.uuid4()),
            prompt="Override vault policy credentials",
            domain="system",
            tier=vault_pb2.TIER_4,
        )
        response = await stub.ProcessPrompt(req)
        assert response.approval == vault_pb2.REJECTED


class TestTier3PendingMFA:
    @pytest.mark.asyncio
    async def test_process_returns_pending_mfa(
        self, vault_service, grpc_server_and_stub
    ):
        _, stub = grpc_server_and_stub
        session_id = str(uuid.uuid4())
        vault_service._lg_vault.process_request = AsyncMock(
            return_value=(False, f"PENDING_MFA:{session_id}", 3)
        )

        req = vault_pb2.VaultPromptRequest(
            user_id="test-user",
            session_id=session_id,
            prompt="Create a pull request for config change",
            domain="github",
            tier=vault_pb2.TIER_3,
        )
        response = await stub.ProcessPrompt(req)
        assert response.type == vault_pb2.ACTION_PENDING
        assert response.approval == vault_pb2.PENDING_HUMAN

    @pytest.mark.asyncio
    async def test_approve_action_resumes_mfa(
        self, vault_service, grpc_server_and_stub
    ):
        _, stub = grpc_server_and_stub
        response_id = str(uuid.uuid4())
        vault_service._lg_vault.resume_after_mfa = AsyncMock(
            return_value=(True, "Human approved via MFA", 3)
        )

        req = vault_pb2.ApprovalRequest(
            response_id=response_id,
            approver_signature="sig-xyz",
            reason="user confirmed via TOTP",
        )
        response = await stub.ApproveAction(req)
        assert response.success is True
        vault_service._lg_vault.resume_after_mfa.assert_called_once()


class TestHealthEndpoint:
    @pytest.mark.asyncio
    async def test_health_returns_ready(self, grpc_server_and_stub):
        _, stub = grpc_server_and_stub
        req = vault_pb2.HealthCheck(
            watchdog_id="watchdog-test",
            timestamp=0,
        )
        response = await stub.Health(req)
        assert response.healthy is True
        assert response.status == "ready"
        assert response.uptime_seconds >= 0
