"""
Generated gRPC service stubs from muscle.proto
(Auto-generated by protoc --grpc_python_out=. muscle.proto)
"""

import grpc
from typing import AsyncIterator
import muscle_pb2


class MuscleServicer(object):
    """Service abstract base class."""
    
    async def GenerateResponse(
        self,
        request: muscle_pb2.PromptRequest,
        context: grpc.aio.ServicerContext
    ) -> AsyncIterator[muscle_pb2.TokenResponse]:
        """Stream tokens from Ollama."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    async def Health(
        self,
        request: muscle_pb2.HealthRequest,
        context: grpc.aio.ServicerContext
    ) -> muscle_pb2.HealthResponse:
        """Health check."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
    
    async def GetActivityStatus(
        self,
        request: muscle_pb2.ActivityStatusRequest,
        context: grpc.aio.ServicerContext
    ) -> muscle_pb2.ActivityStatusResponse:
        """Get activity status."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


class MuscleStub(object):
    """Client stub for calling Muscle service."""
    
    def __init__(self, channel: grpc.aio.Channel):
        self.channel = channel
        self.GenerateResponse = channel.unary_stream(
            '/muscle.api.Muscle/GenerateResponse',
            request_serializer=muscle_pb2.PromptRequest.SerializeToString,
            response_deserializer=muscle_pb2.TokenResponse.FromString,
        )
        self.Health = channel.unary_unary(
            '/muscle.api.Muscle/Health',
            request_serializer=muscle_pb2.HealthRequest.SerializeToString,
            response_deserializer=muscle_pb2.HealthResponse.FromString,
        )
        self.GetActivityStatus = channel.unary_unary(
            '/muscle.api.Muscle/GetActivityStatus',
            request_serializer=muscle_pb2.ActivityStatusRequest.SerializeToString,
            response_deserializer=muscle_pb2.ActivityStatusResponse.FromString,
        )


def add_MuscleServicer_to_server(servicer: MuscleServicer, server: grpc.aio.Server):
    """Register Muscle servicer with gRPC server."""
    rpc_method_handlers = {
        # GenerateResponse is unary request -> streaming response.
        'GenerateResponse': grpc.unary_stream_rpc_method_handler(
            servicer.GenerateResponse,
            request_deserializer=muscle_pb2.PromptRequest.FromString,
            response_serializer=muscle_pb2.TokenResponse.SerializeToString,
        ),
        'Health': grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=muscle_pb2.HealthRequest.FromString,
            response_serializer=muscle_pb2.HealthResponse.SerializeToString,
        ),
        'GetActivityStatus': grpc.unary_unary_rpc_method_handler(
            servicer.GetActivityStatus,
            request_deserializer=muscle_pb2.ActivityStatusRequest.FromString,
            response_serializer=muscle_pb2.ActivityStatusResponse.SerializeToString,
        ),
    }

    generic_handler = grpc.method_handlers_generic_handler(
        'muscle.api.Muscle',
        rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
