"""
Generated Python gRPC stubs from muscle.proto
(Auto-generated by protoc --python_out=. muscle.proto)

This file should be regenerated if muscle.proto changes:
  protoc --python_out=cmd/muscle --grpc_python_out=cmd/muscle ../api/muscle.proto
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import descriptor_pb2
from typing import ClassVar as _ClassVar, Optional as _Optional, Mapping as _Mapping

DESCRIPTOR: _descriptor.FileDescriptor

class PromptRequest(_message.Message):
    """Request from Pi to Muscle for token generation."""
    __slots__ = ('session_id', 'prompt', 'system_context', 'history', 'config', 'action_intent', 'constraints')
    
    SESSION_ID_FIELD_NUMBER: _ClassVar[int]
    PROMPT_FIELD_NUMBER: _ClassVar[int]
    SYSTEM_CONTEXT_FIELD_NUMBER: _ClassVar[int]
    HISTORY_FIELD_NUMBER: _ClassVar[int]
    CONFIG_FIELD_NUMBER: _ClassVar[int]
    ACTION_INTENT_FIELD_NUMBER: _ClassVar[int]
    CONSTRAINTS_FIELD_NUMBER: _ClassVar[int]
    
    session_id: str
    prompt: str
    system_context: str
    action_intent: str
    
    def __init__(
        self,
        *,
        session_id: _Optional[str] = ...,
        prompt: _Optional[str] = ...,
        system_context: _Optional[str] = ...,
        history: _Optional[list] = ...,
        config: _Optional['InferenceConfig'] = ...,
        action_intent: _Optional[str] = ...,
        constraints: _Optional[_Mapping[str, str]] = ...,
    ) -> None: ...

class Message(_message.Message):
    """Conversation history entry."""
    __slots__ = ('role', 'content')
    
    ROLE_FIELD_NUMBER: _ClassVar[int]
    CONTENT_FIELD_NUMBER: _ClassVar[int]
    
    role: str
    content: str
    
    def __init__(
        self,
        *,
        role: _Optional[str] = ...,
        content: _Optional[str] = ...,
    ) -> None: ...

class InferenceConfig(_message.Message):
    """Inference parameters."""
    __slots__ = ('temperature', 'top_k', 'top_p', 'max_tokens', 'stream')
    
    TEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    TOP_K_FIELD_NUMBER: _ClassVar[int]
    TOP_P_FIELD_NUMBER: _ClassVar[int]
    MAX_TOKENS_FIELD_NUMBER: _ClassVar[int]
    STREAM_FIELD_NUMBER: _ClassVar[int]
    
    temperature: float
    top_k: int
    top_p: float
    max_tokens: int
    stream: bool
    
    def __init__(
        self,
        *,
        temperature: _Optional[float] = ...,
        top_k: _Optional[int] = ...,
        top_p: _Optional[float] = ...,
        max_tokens: _Optional[int] = ...,
        stream: _Optional[bool] = ...,
    ) -> None: ...

class TokenResponse(_message.Message):
    """Response from Muscle: a single token."""
    __slots__ = ('token', 'token_index', 'is_complete', 'metadata', 'status', 'error_msg')
    
    TOKEN_FIELD_NUMBER: _ClassVar[int]
    TOKEN_INDEX_FIELD_NUMBER: _ClassVar[int]
    IS_COMPLETE_FIELD_NUMBER: _ClassVar[int]
    METADATA_FIELD_NUMBER: _ClassVar[int]
    STATUS_FIELD_NUMBER: _ClassVar[int]
    ERROR_MSG_FIELD_NUMBER: _ClassVar[int]
    
    token: str
    token_index: int
    is_complete: bool
    status: str
    error_msg: str
    metadata: 'ResponseMetadata'
    
    def __init__(
        self,
        *,
        token: _Optional[str] = ...,
        token_index: _Optional[int] = ...,
        is_complete: _Optional[bool] = ...,
        metadata: _Optional['ResponseMetadata'] = ...,
        status: _Optional[str] = ...,
        error_msg: _Optional[str] = ...,
    ) -> None: ...

class ResponseMetadata(_message.Message):
    """Metadata about the inference response."""
    __slots__ = ('confidence', 'reasoning_steps', 'tokens_used', 'inference_time_ms', 'model_name')
    
    CONFIDENCE_FIELD_NUMBER: _ClassVar[int]
    REASONING_STEPS_FIELD_NUMBER: _ClassVar[int]
    TOKENS_USED_FIELD_NUMBER: _ClassVar[int]
    INFERENCE_TIME_MS_FIELD_NUMBER: _ClassVar[int]
    MODEL_NAME_FIELD_NUMBER: _ClassVar[int]
    
    confidence: float
    tokens_used: int
    inference_time_ms: float
    model_name: str
    reasoning_steps: list
    
    def __init__(
        self,
        *,
        confidence: _Optional[float] = ...,
        reasoning_steps: _Optional[list] = ...,
        tokens_used: _Optional[int] = ...,
        inference_time_ms: _Optional[float] = ...,
        model_name: _Optional[str] = ...,
    ) -> None: ...

class HealthRequest(_message.Message):
    """Health check request."""
    __slots__ = ('session_id',)
    
    SESSION_ID_FIELD_NUMBER: _ClassVar[int]
    session_id: str
    
    def __init__(self, *, session_id: _Optional[str] = ...) -> None: ...

class HealthResponse(_message.Message):
    """Health check response."""
    __slots__ = ('healthy', 'status', 'uptime_seconds', 'model_loaded')
    
    HEALTHY_FIELD_NUMBER: _ClassVar[int]
    STATUS_FIELD_NUMBER: _ClassVar[int]
    UPTIME_SECONDS_FIELD_NUMBER: _ClassVar[int]
    MODEL_LOADED_FIELD_NUMBER: _ClassVar[int]
    
    healthy: bool
    status: str
    uptime_seconds: int
    model_loaded: str
    
    def __init__(
        self,
        *,
        healthy: _Optional[bool] = ...,
        status: _Optional[str] = ...,
        uptime_seconds: _Optional[int] = ...,
        model_loaded: _Optional[str] = ...,
    ) -> None: ...

class ActivityStatusRequest(_message.Message):
    """Request for activity status."""
    __slots__ = ('session_id',)
    
    SESSION_ID_FIELD_NUMBER: _ClassVar[int]
    session_id: str
    
    def __init__(self, *, session_id: _Optional[str] = ...) -> None: ...

class ActivityStatusResponse(_message.Message):
    """Response: system activity status."""
    __slots__ = ('idle_status', 'queue_depth', 'queue_capacity', 'accepting_requests', 'gpu_utilization_percent', 'idle_duration_seconds', 'user_active')
    
    IDLE_STATUS_FIELD_NUMBER: _ClassVar[int]
    QUEUE_DEPTH_FIELD_NUMBER: _ClassVar[int]
    QUEUE_CAPACITY_FIELD_NUMBER: _ClassVar[int]
    ACCEPTING_REQUESTS_FIELD_NUMBER: _ClassVar[int]
    GPU_UTILIZATION_PERCENT_FIELD_NUMBER: _ClassVar[int]
    IDLE_DURATION_SECONDS_FIELD_NUMBER: _ClassVar[int]
    USER_ACTIVE_FIELD_NUMBER: _ClassVar[int]
    
    idle_status: str           # "active", "transitioning", "idle"
    queue_depth: int
    queue_capacity: int
    accepting_requests: bool
    gpu_utilization_percent: float
    idle_duration_seconds: int
    user_active: bool
    
    def __init__(
        self,
        *,
        idle_status: _Optional[str] = ...,
        queue_depth: _Optional[int] = ...,
        queue_capacity: _Optional[int] = ...,
        accepting_requests: _Optional[bool] = ...,
        gpu_utilization_percent: _Optional[float] = ...,
        idle_duration_seconds: _Optional[int] = ...,
        user_active: _Optional[bool] = ...,
    ) -> None: ...
